### ISSUE TITLE
State of project

### ISSUE THREAD

**Issue by CodeFatherG** [KooleControls/ESPTool#6]
Hi!

I am wondering the state of this project?

The landing readme would indicate that the project is still in development https://github.com/KooleControls/ESPTool/blob/main/README.md?plain=1#L4

Hoeever, it looks like the project has not seen any development in 3 years (Except the OTA feature)? https://github.com/KooleControls/ESPTool/blame/main/ESPTool/ESPTool.cs

**Comment by vanBassum** [comment]
There is no active development on this project anymore. Because It does what it needs to do for us. We have been using this for a couple of years now in our production line to program our devices.

I don't see any development happening in the near future. I should update the readme. In the meantime im happy to merge pull requests if they arise.
